---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.1
jobs:
  deploy_dev:
    executor: aws-cli/default
    environment:
      ECS_CLUSTER: test
      ECS_SERVICE: wordpress
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_dev
      - run:
          name: Deploy over SSH
          command: |
            scp -P $SSH_PORT -o StrictHostKeyChecking=accept-new composer.json $SSH_USER@$SSH_HOST_DEV:$SSH_DEV_PATH
  deploy_stage:
    executor: aws-cli/default
    environment:
      ECS_CLUSTER: test
      ECS_SERVICE: wordpress
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_stage
      - run:
          name: Deploy over SSH
          command: |
            scp -P $SSH_PORT -o StrictHostKeyChecking=accept-new composer.json $SSH_USER@$SSH_HOST_STAGE:$SSH_PATH

  deploy_prod:
    environment:
      ECS_CLUSTER: prod
      ECS_SERVICE: wordpress
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: wordpress_prod
      - run:
          name: Deploy over SSH
          command: |
            scp -P $SSH_PORT -o StrictHostKeyChecking=accept-new composer.json $SSH_USER@$SSH_HOST_PROD:$SSH_PATH

workflows:
  version: 2
  pipeline:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: development
      - deploy_stage:
          filters:
            branches:
              only: staging
      - deploy_prod:
          filters:
            branches:
              only: main
